=== conuti-gmbh/bo4e-schema-en/schemas/v1/bo/AdHocControlChannel.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/AdHocSteuerkanal.schema.json",
  "title": "AdHocControlChannel",
  "type": "object",
  "properties": {
    "boType": {
      "$ref": "../enum/BOType.schema.json",
      "default": "AD_HOC_CONTROL_CHANNEL"
    },
    "structureVersion": {
      "type": "string",
      "default": "1",
      "description": "versionStruktur"
    },
    "configurationProduct": {
      "type": "string",
      "faker": {
        "string.numeric": 14
      },
      "description": "konfigurationsprodukt"
    },
    "targetAddress": {
      "$ref": "../com/TargetAddress.schema.json"
    },
    "issuer": {
      "$ref": "../com/Issuer.schema.json"
    },
    "certificateUser": {
      "$ref": "../com/CertificateUser.schema.json"
    },
    "IpAddressClsDevice": {
      "$ref": "../com/IpAddressClsDevice.schema.json"
    }
  },
  "required": [
    "boType",
    "structureVersion"
  ]
}

=== conuti-gmbh/bo4e-schema-en/docs/examples/bo/AdHocControlChannel.json
{
  "boType": "AD_HOC_CONTROL_CHANNEL",
  "structureVersion": "1",
  "configurationProduct": "04300570676214",
  "targetAddress": {
    "targetAddress1": "commodo sit mollit reprehenderit",
    "targetAddress2": "qui",
    "targetAddress3": "labore nisi fugiat laboris sed",
    "targetAddress4": "dolor sint nisi quis",
    "targetAddress5": "Lorem quis ut"
  },
  "issuer": {
    "issuer1": "ut esse aliquip commodo",
    "issuer2": "cupidatat aliqua tempor culpa",
    "issuer3": "dolore velit ea",
    "issuer4": "ut tempor sed",
    "issuer5": "in mollit occaecat"
  },
  "certificateUser": {
    "certificateUser1": "dolor sunt enim eu",
    "certificateUser2": "commodo do non",
    "certificateUser3": "mollit",
    "certificateUser4": "eiusmod pariatur proident",
    "certificateUser5": "velit nisi dolor"
  },
  "IpAddressClsDevice": {
    "IpAddressClsDevice1": "culpa",
    "IpAddressClsDevice2": "ipsum pariatur exercitation anim",
    "IpAddressClsDevice3": "Ut ad irure aliqua deserunt",
    "IpAddressClsDevice4": "pariatur aute",
    "IpAddressClsDevice5": "proident sed Ut laboris"
  }
}
