=== conuti-gmbh/bo4e-schema-en/schemas/v1/bo/DisconnectionOrder.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/Sperraufrag.schema.json",
  "title": "DisconnectionOrder",
  "type": "object",
  "properties": {
    "boType": {
      "$ref": "../enum/BOType.schema.json",
      "default": "DISCONNECTION_ORDER"
    },
    "structureVersion": {
      "type": "string",
      "default": "1",
      "description": "versionStruktur"
    },
    "meetingPoint": {
      "$ref": "../com/Address.schema.json"
    },
    "disconnectionOrderType": {
      "$ref": "../enum/DisconnectionOrderType.schema.json",
      "description": "Handelt es sich um einen Auftrag zum SPERREN oder ENTSPERREN?"
    },
    "disconnectionOrderStatus": {
      "$ref": "../enum/OrderStatus.schema.json",
      "description": "Auftragsstatus"
    },
    "disconnectionOrderRejectionReason": {
      "$ref": "../enum/DisconnectionOrderRejectionReason.schema.json",
      "description": "Falls Sperrauftragsstatus = ABGELEHNT"
    },
    "disconnectionPreventionReason": {
      "$ref": "../enum/DisconnectionPreventionReason.schema.json",
      "description": "Falls Sperrauftragsstatus = GESCHEITERT"
    },
    "meterNumber": {
      "type": "string",
      "faker": {
        "string.binary": {
          "prefix": "ZAEHLER_",
          "length": 6
        }
      },
      "description": "Die Nummer des zu sperrenden Zählers"
    },
    "isOrderedByBailiff": {
      "type": "boolean",
      "description": "True, falls die Sperrung vom Gerichtsvollzieher angeordnet ist."
    }
  },
  "required": [
    "boType",
    "structureVersion"
  ]
}

=== conuti-gmbh/bo4e-schema-en/docs/examples/bo/DisconnectionOrder.json
{
  "boType": "DISCONNECTION_ORDER",
  "structureVersion": "1",
  "meetingPoint": {
    "postalCode": "61396",
    "city": "Nord Linn",
    "street": "Friesenweg",
    "houseNumber": "84c",
    "poBox": "commodo esse",
    "addressSupplement": "cupidatat sunt ea",
    "coSupplement": "id aliquip deserunt laboris fugiat",
    "countryCode": "AG",
    "district": "Neu Jamie",
    "additionalInformation": {
      "supplement1": "sit quis consectetur laborum Ut",
      "supplement2": "dolor reprehenderit cillum non ullamco",
      "supplement3": "proident ex eiusmod Ut",
      "supplement4": "laboris et sunt id in",
      "supplement5": "labore ex qui nisi"
    }
  },
  "disconnectionOrderType": "UNLOCK",
  "disconnectionOrderStatus": "ENFG_ELECTRICALLY_DRIVEN_HEAT_PUMPS",
  "disconnectionOrderRejectionReason": "OTHER_FUTURE_SUPPLIER",
  "disconnectionPreventionReason": "ACTUAL_PREVENTION_REASON",
  "meterNumber": "ZAEHLER_000010",
  "isOrderedByBailiff": true
}
