=== conuti-gmbh/bo4e-schema-en/schemas/v1/bo/LocationBundle.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema-en/main/schemas/v1/bo/LocationBundle.schema.json",
  "title": "LocationBundle",
  "type": "object",
  "properties": {
    "boType": {
      "$ref": "../enum/BOType.schema.json",
      "default": "LOCATION_BUNDLE"
    },
    "structureVersion": {
      "type": "string",
      "default": "1"
    },
    "locationBundleStructureId": {
      "type": "string",
      "faker": {
        "string.numeric": 11
      }
    },
    "locationBundleNumber": {
      "type": "integer"
    },
    "standardizedLocationBundleStructure": {
      "type": "boolean"
    },
    "dataQuality": {
      "$ref": "../enum/DataQuality.schema.json"
    },
    "validityPeriod": {
      "$ref": "../com/TimePeriod.schema.json"
    },
    "assignmentObjectCode": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "../com/AssignmentObjectCode.schema.json"
      }
    }
  },
  "required": [
    "boType",
    "structureVersion"
  ]
}

=== conuti-gmbh/bo4e-schema-en/docs/examples/bo/LocationBundle.json
{
  "boType": "LOCATION_BUNDLE",
  "structureVersion": "1",
  "locationBundleStructureId": "11239309345",
  "locationBundleNumber": -48020006,
  "standardizedLocationBundleStructure": true,
  "dataQuality": "DATA_PRESENT_IN_SYSTEM",
  "validityPeriod": {
    "timeUnit": "SECOND",
    "duration": 5,
    "startDate": "1907-11-21T03:03:01.0Z",
    "endDate": "1940-08-04T07:15:36.0Z",
    "unit": "HALF_YEAR",
    "readingPeriod": "645835",
    "billingPeriod": "339596",
    "periodText": "cupidatat",
    "periodId": 5
  },
  "assignmentObjectCode": [
    {
      "referenceLocationType": "MALO",
      "referenceLocationId": "39449156925",
      "upstreamLocationType": "MALO",
      "upstreamLocationId": "56609062821",
      "objectCode": [
        {
          "objectCode": "CODE_100011",
          "locationBundleNumber": 9
        }
      ],
      "referenceMarketLocationTechnicalResource": [
        "93950310555"
      ]
    }
  ]
}
