=== conuti-gmbh/bo4e-schema-en/schemas/v1/bo/MeteringTimeDefinition.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/Zaehlzeitdefinition.schema.json",
  "title": "MeteringTimeDefinition",
  "type": "object",
  "properties": {
    "boType": {
      "$ref": "../enum/BOType.schema.json",
      "default": "METERING_TIME_DEFINITION"
    },
    "structureVersion": {
      "type": "string",
      "default": "1",
      "description": "versionStruktur"
    },
    "beginDate": {
      "type": "string",
      "format": "date-time",
      "description": "Der inklusive Zeitpunkt ab dem die Zaehlzeitdefinitionen ausgerollt sind"
    },
    "closingDate": {
      "type": "string",
      "format": "date-time",
      "description": "Der exklusive Zeitpunkt bis zu dem die Zaehlzeitdefinitionen ausgerollt sind"
    },
    "version": {
      "type": "string",
      "format": "date-time",
      "description": "Version der Zählzeitdefinition als Datum"
    },
    "necessity": {
      "$ref": "../enum/DefinitionsNecessity.schema.json",
      "description": "Beschreibt ob eine Zaehlzeitdefinitionen notwendig ist"
    },
    "versionSpecification": {
      "type": "string",
      "faker": {
        "string.binary": {
          "prefix": "VERSION_",
          "length": 6
        }
      },
      "description": "versionsangabe"
    },
    "code": {
      "type": "string",
      "faker": {
        "string.binary": {
          "prefix": "CODE_",
          "length": 6
        }
      },
      "description": "Zählzeitdefinition"
    },
    "meteringTimes": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "../com/MeteringTime.schema.json"
      },
      "description": "Liste der Zählzeiten [1 - 99999]"
    },
    "meteringTimeRegister": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "../com/MeteringTimeRegister.schema.json"
      },
      "description": "Liste der Zählzeitregister"
    }
  },
  "required": [
    "boType",
    "structureVersion"
  ]
}

=== conuti-gmbh/bo4e-schema-en/docs/examples/bo/MeteringTimeDefinition.json
{
  "boType": "METERING_TIME_DEFINITION",
  "structureVersion": "1",
  "beginDate": "1943-08-30T11:22:53.0Z",
  "closingDate": "1924-04-10T06:58:40.0Z",
  "version": "1958-12-20T02:12:52.0Z",
  "necessity": "METERING_TIME_DEFINITIONS_USED",
  "versionSpecification": "VERSION_101010",
  "code": "CODE_110101",
  "meteringTimes": [
    {
      "code": "CODE_110001",
      "frequency": "ANNUAL",
      "transmissibility": "ELECTRONIC",
      "peakLoadDetermination": "NO_USE_OF_PEAK_LOAD_WINDOW",
      "isOrderable": true,
      "typeValue": "HEAT_PUMP",
      "descriptionType": "aliquip esse adipisicing eiusmod mollit",
      "changeTimestamp": "1938-01-19T18:10:58.0Z",
      "register": "officia occaecat"
    }
  ],
  "meteringTimeRegister": [
    {
      "register": "cillum in consectetur sunt culpa",
      "meteringTimeDefinition": "aute",
      "offPeakCapable": "OFF_PEAK_CAPABLE"
    }
  ]
}
