=== conuti-gmbh/bo4e-schema-en/schemas/v1/bo/Offer.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema-en/main/schemas/v1/bo/Offer.schema.json",
  "title": "Offer",
  "type": "object",
  "properties": {
    "boType": {
      "$ref": "../enum/BOType.schema.json",
      "default": "OFFER"
    },
    "structureVersion": {
      "type": "string",
      "default": "1"
    },
    "offerNumber": {
      "type": "string",
      "faker": {
        "string.numeric": 3
      }
    },
    "requestReference": {
      "type": "string",
      "faker": {
        "string.binary": {
          "prefix": "REF",
          "length": 6
        }
      }
    },
    "offerDate": {
      "type": "string",
      "format": "date-time"
    },
    "sector": {
      "$ref": "../enum/Sector.schema.json"
    },
    "bindingPeriod": {
      "type": "string",
      "format": "date-time"
    },
    "offerGiver": {
      "$ref": "../bo/BusinessPartner.schema.json"
    },
    "offerRecipient": {
      "$ref": "../bo/BusinessPartner.schema.json"
    },
    "signatoryOfferRecipient": {
      "$ref": "../bo/ContactPerson.schema.json"
    },
    "signatoryOfferGiver": {
      "$ref": "../bo/ContactPerson.schema.json"
    },
    "setupTransmissionPeriod": {
      "$ref": "../com/TimePeriod.schema.json"
    },
    "offerBindingPeriod": {
      "$ref": "../com/TimePeriod.schema.json"
    },
    "variants": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "../com/OfferVariant.schema.json"
      }
    },
    "positionData": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "../com/OfferPosition.schema.json"
      }
    }
  },
  "required": [
    "boType",
    "structureVersion"
  ]
}

=== conuti-gmbh/bo4e-schema-en/docs/examples/bo/Offer.json
{
  "boType": "OFFER",
  "structureVersion": "1",
  "offerNumber": "326",
  "requestReference": "REF110011",
  "offerDate": "1895-05-22T17:23:55.0Z",
  "sector": "DISTRICT_HEATING",
  "bindingPeriod": "1945-06-18T20:28:19.0Z",
  "offerGiver": {
    "boType": "BUSINESS_PARTNER",
    "structureVersion": "1",
    "salutation": "Prof. Dr.",
    "name1": "Schönfeld",
    "name2": "Carlotta",
    "name3": "culpa ex",
    "name4": "est laboris do",
    "vatId": "DE011100010",
    "creditorId": "414564",
    "emailAddress": "Collien_Dutkiewicz32@gmail.com",
    "website": "https://wild-museum.ch",
    "commercialClassification": true,
    "commercialRegisterNumber": "035350",
    "courtOfRegistration": "Landshut",
    "partnerAddress": {
      "postalCode": "64772",
      "city": "Bad Enricoland",
      "street": "Rudolf-Stracke-Str.",
      "houseNumber": "2",
      "poBox": "dolor reprehenderit",
      "addressSupplement": "est nisi",
      "coSupplement": "amet incididunt cupidatat ad",
      "countryCode": "FX",
      "district": "Nord Diego",
      "additionalInformation": {
        "supplement1": "nulla dolor labore est fugiat",
        "supplement2": "laborum exercitation et mollit",
        "supplement3": "veniam eu in",
        "supplement4": "irure",
        "supplement5": "cupidatat laborum"
      }
    },
    "externalCustomerNumberSupplier": "510450",
    "externalReferences": [
      {
        "externalReferenceName": "Kundennummer beim Lieferanten",
        "externalReferenceValue": "4259211482"
      }
    ],
    "businessPartnerRole": [
      "PROSPECT"
    ],
    "contactChannel": [
      "PHONE_CALL"
    ],
    "contactPerson": {
      "boType": "CONTACT_PERSON",
      "structureVersion": "1",
      "lastName": "Szendrei",
      "eMailAddress": "Niklas69@gmail.com",
      "phoneNumbers": [
        {
          "numberType": "COLLECTIVE_PHONE",
          "phoneNumber": "(0217) 182814978"
        }
      ]
    }
  },
  "offerRecipient": {
    "boType": "BUSINESS_PARTNER",
    "structureVersion": "1",
    "salutation": "Prof. Dr.",
    "name1": "Lutje",
    "name2": "Matthis",
    "name3": "dolor",
    "name4": "nisi ullamco deserunt ipsum veniam",
    "vatId": "DE010000001",
    "creditorId": "881758",
    "emailAddress": "Marian_Schniedermeier93@yahoo.com",
    "website": "https://berufen-chemie.name/",
    "commercialClassification": true,
    "commercialRegisterNumber": "814094",
    "courtOfRegistration": "Figlstadt",
    "partnerAddress": {
      "postalCode": "62961",
      "city": "Reussland",
      "street": "Borsigstr.",
      "houseNumber": "15a",
      "poBox": "nostrud Excepteur est",
      "addressSupplement": "et ullamco",
      "coSupplement": "Lorem",
      "countryCode": "MF",
      "district": "West Riccardoburg",
      "additionalInformation": {
        "supplement1": "sit veniam",
        "supplement2": "fugiat in aute dolore sunt",
        "supplement3": "ipsum et",
        "supplement4": "qui ut laboris amet",
        "supplement5": "ut do in"
      }
    },
    "externalCustomerNumberSupplier": "160207",
    "externalReferences": [
      {
        "externalReferenceName": "Kundennummer beim Altlieferanten",
        "externalReferenceValue": "0849957886"
      }
    ],
    "businessPartnerRole": [
      "READING_CARD_RECIPIENT"
    ],
    "contactChannel": [
      "FAX"
    ],
    "contactPerson": {
      "boType": "CONTACT_PERSON",
      "structureVersion": "1",
      "lastName": "Illing",
      "eMailAddress": "Thies28@yahoo.com",
      "phoneNumbers": [
        {
          "numberType": "FAX_EXTENSION",
          "phoneNumber": "+49-8263-73311959"
        }
      ]
    }
  },
  "signatoryOfferRecipient": {
    "boType": "CONTACT_PERSON",
    "structureVersion": "1",
    "lastName": "Marten",
    "eMailAddress": "Elia.Reinhardt1@yahoo.com",
    "phoneNumbers": [
      {
        "numberType": "DEPARTMENT_PHONE",
        "phoneNumber": "(0356) 120836138"
      }
    ]
  },
  "signatoryOfferGiver": {
    "boType": "CONTACT_PERSON",
    "structureVersion": "1",
    "lastName": "Baarck",
    "eMailAddress": "Jaden1@gmail.com",
    "phoneNumbers": [
      {
        "numberType": "MOBILE_NUMBER",
        "phoneNumber": "(0525) 812025435"
      }
    ]
  },
  "setupTransmissionPeriod": {
    "timeUnit": "MONTH",
    "duration": 10,
    "startDate": "1965-03-22T01:02:01.0Z",
    "endDate": "1929-08-11T21:05:36.0Z",
    "unit": "SECOND",
    "readingPeriod": "565358",
    "billingPeriod": "895343",
    "periodText": "sed cupidatat aute nostrud anim",
    "periodId": 3
  },
  "offerBindingPeriod": {
    "timeUnit": "WEEK",
    "duration": 0,
    "startDate": "1963-04-26T05:05:15.0Z",
    "endDate": "1927-04-06T09:41:34.0Z",
    "unit": "DAY",
    "readingPeriod": "535738",
    "billingPeriod": "017919",
    "periodText": "Duis esse deserunt elit",
    "periodId": 3
  },
  "variants": [
    {
      "offerStatus": "COMPLETED",
      "description": "minim magna",
      "creationDate": "1939-08-12T10:47:34.0Z",
      "bindingPeriod": "1913-12-05T05:48:58.0Z",
      "totalQuantity": {
        "value": 4.75,
        "unit": "VAR"
      },
      "totalCosts": {
        "value": 6.25,
        "currency": "do sit voluptate irure"
      },
      "parts": [
        {
          "requestSubReference": "ANSUBREF1101",
          "offerPartTotalQuantity": {
            "value": 5,
            "unit": "Z16"
          },
          "offerPartTotalCosts": {
            "value": 9.75,
            "currency": "velit aliquip aliqua labore Duis"
          },
          "deliveryPeriod": {
            "timeUnit": "QUARTER",
            "duration": 4,
            "startDate": "1939-03-16T18:57:22.0Z",
            "endDate": "1904-05-25T23:49:12.0Z",
            "unit": "MINUTE",
            "readingPeriod": "494831",
            "billingPeriod": "468169",
            "periodText": "aliquip officia ea ex",
            "periodId": 4
          },
          "referenceCatalogNumber": {
            "catalogNumber": "10758",
            "lineNumber": "00291",
            "versionNumber": "92217"
          },
          "deliveryPointOfferPart": [
            {
              "boType": "MARKET_LOCATION",
              "structureVersion": "1",
              "marketLocationId": "24168215437",
              "sector": "consectetur cupidatat elit labore",
              "energyDirection": "FEED_IN",
              "balancingMethod": "SLP",
              "consumptionType": [
                "SB"
              ],
              "interruptible": false,
              "gridLevel": "HSP_MSP_UMSP",
              "transformation": "HSP_MSP_UMSP",
              "gridOperatorCodeNumber": "0551148473",
              "areaType": "TRANSMISSION_GRID",
              "gridAreaNumber": "0869493946",
              "balancingArea": "in quis officia aliqua",
              "defaultSupplierCodeNumber": "5143748359",
              "gasQuality": "H_GAS",
              "endCustomer": {
                "boType": "BUSINESS_PARTNER",
                "structureVersion": "1",
                "salutation": "Dr.",
                "name1": "Tremmel",
                "name2": "Malte",
                "name3": "anim",
                "name4": "proident sit consectetur ipsum",
                "vatId": "DE101101000",
                "creditorId": "900208",
                "emailAddress": "Jonna.Markowski@yahoo.com",
                "website": "https://vortrefflich-junge.de/",
                "commercialClassification": false,
                "commercialRegisterNumber": "639891",
                "courtOfRegistration": "Shawnland",
                "partnerAddress": {
                  "postalCode": "78807",
                  "city": "Lippedorf",
                  "street": "Hans-Schlehahn-Str.",
                  "houseNumber": "7",
                  "poBox": "sunt in eu",
                  "addressSupplement": "dolor Lorem ut",
                  "coSupplement": "aliqua ullamco id",
                  "countryCode": "KM",
                  "district": "Neu Mariastadt",
                  "additionalInformation": {
                    "supplement1": "ullamco Excepteur anim proident ad",
                    "supplement2": "sint ut",
                    "supplement3": "sunt aute ullamco",
                    "supplement4": "qui nulla irure",
                    "supplement5": "aute ea ullamco aliquip"
                  }
                },
                "externalCustomerNumberSupplier": "733982",
                "externalReferences": [
                  {
                    "externalReferenceName": "Kundennummer beim Altlieferanten",
                    "externalReferenceValue": "4900372789"
                  }
                ],
                "businessPartnerRole": [
                  "MARKET_PARTNER"
                ],
                "contactChannel": [
                  "FAX"
                ],
                "contactPerson": {
                  "boType": "CONTACT_PERSON",
                  "structureVersion": "1",
                  "lastName": "Green",
                  "eMailAddress": "Tino.Kinzel@gmail.com",
                  "phoneNumbers": [
                    {
                      "numberType": "FAX_CENTRAL",
                      "phoneNumber": "(0767) 813709880"
                    }
                  ]
                }
              },
              "locationAddress": {
                "postalCode": "49089",
                "city": "Schweinfurt",
                "street": "Oskar-Moll-Str.",
                "houseNumber": "60c",
                "poBox": "laboris eu laborum mollit",
                "addressSupplement": "pariatur ut anim dolor",
                "coSupplement": "nostrud",
                "countryCode": "MM",
                "district": "Alt Luc",
                "additionalInformation": {
                  "supplement1": "ipsum anim",
                  "supplement2": "adipisicing in eu",
                  "supplement3": "sunt",
