=== conuti-gmbh/bo4e-schema-en/schemas/v1/bo/Order.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/Auftrag.schema.json",
  "title": "Order",
  "type": "object",
  "properties": {
    "boType": {
      "$ref": "../enum/BOType.schema.json",
      "default": "ORDER"
    },
    "structureVersion": {
      "type": "string",
      "default": "1",
      "description": "versionStruktur"
    },
    "executionDate": {
      "type": "string",
      "format": "date-time",
      "description": "Das Ausführungsdatum beschreibt zu welchem Zeitpunkt ein Auftrag ausgeführt werden soll."
    },
    "completionDate": {
      "type": "string",
      "format": "date-time",
      "description": "Das Fertigstellungsdatum beschreibt zu welchem Zeitpunkt ein Auftrag ausgeführt wurde/wird."
    },
    "startDate": {
      "type": "string",
      "format": "date-time",
      "description": "Das Startdatum beschreibt zu welchem Zeitpunkt ein Auftrag gestartet wurde/wird."
    },
    "endDate": {
      "type": "string",
      "format": "date-time",
      "description": "Das Enddatum beschreibt zu welchem Zeitpunkt ein Auftrag endete oder enden wird."
    },
    "sector": {
      "$ref": "../enum/Sector.schema.json",
      "description": "Die Sparte in der der Auftrag relevant ist"
    },
    "deliveryAddress": {
      "$ref": "../com/Address.schema.json",
      "description": "Die Adresse, die sich in Belieferung befindet."
    },
    "marketLocationId": {
      "type": "string",
      "faker": {
        "string.numeric": 11
      },
      "description": "Die ID der Marktlokation der der zu sperrende Zähler zugeordnet ist."
    },
    "minimumPrice": {
      "$ref": "../com/Price.schema.json",
      "description": "Der Mindestpreis eines Auftrags (z.B. für eine Sperrung)"
    },
    "maximumPrice": {
      "$ref": "../com/Price.schema.json",
      "description": "Der Höchstpreis eines Auftrags (z.B. für eine Sperrung)"
    },
    "energyDirection": {
      "$ref": "../enum/EnergyDirection.schema.json"
    },
    "calculationPrice": {
      "type": "number",
      "format": "float",
      "faker": {
        "number.float": {
          "multipleOf": 0.25,
          "min": 1,
          "max": 10
        }
      },
      "description": "berechnungspreis"
    },
    "totalSum": {
      "type": "number",
      "format": "float",
      "faker": {
        "number.float": {
          "multipleOf": 0.25,
          "min": 10,
          "max": 20
        }
      },
      "description": "summeGesamt"
    },
    "postponedDeregistrationDate": {
      "type": "string",
      "format": "date-time",
      "description": "verschobenerAbmeldetermin"
    },
    "resolutionTimestamp": {
      "type": "string",
      "format": "date-time",
      "description": "behebungsZeitpunkt"
    },
    "deliveryAddressOldDevices": {
      "$ref": "../bo/BusinessPartner.schema.json"
    },
    "definitionType": {
      "$ref": "../enum/DefinitionType.schema.json"
    },
    "positionData": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "../com/OrderPosition.schema.json"
      },
      "description": "positionsdaten"
    },
    "remarks": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "string",
        "faker": {
          "lorem.sentence": 5
        }
      },
      "description": "bemerkungen"
    }
  },
  "required": [
    "boType",
    "structureVersion"
  ]
}

=== conuti-gmbh/bo4e-schema-en/docs/examples/bo/Order.json
{
  "boType": "ORDER",
  "structureVersion": "1",
  "executionDate": "1963-10-08T02:11:17.0Z",
  "completionDate": "1930-06-18T12:37:01.0Z",
  "startDate": "1950-06-24T03:15:31.0Z",
  "endDate": "1934-02-23T03:45:21.0Z",
  "sector": "GAS",
  "deliveryAddress": {
    "postalCode": "07511",
    "city": "Bergheim",
    "street": "Heinrich-von-Stephan-Str.",
    "houseNumber": "96b",
    "poBox": "ea tempor veniam adipisicing",
    "addressSupplement": "tempor dolor dolor ad",
    "coSupplement": "voluptate sint do amet",
    "countryCode": "BH",
    "district": "Süd Beratdorf",
    "additionalInformation": {
      "supplement1": "dolore ullamco tempor cupidatat id",
      "supplement2": "veniam sed aute",
      "supplement3": "incididunt nisi sed sint sunt",
      "supplement4": "in quis eiusmod Excepteur",
      "supplement5": "Excepteur dolor"
    }
  },
  "marketLocationId": "51543788621",
  "minimumPrice": {
    "value": 7.75,
    "amount": -79309013,
    "unit": "CT",
    "referenceValue": "MWH",
    "status": "PROVISIONAL",
    "priceType": "TRANSACTION_PRICE"
  },
  "maximumPrice": {
    "value": 6,
    "amount": -76054354,
    "unit": "CT",
    "referenceValue": "KVAR",
    "status": "PROVISIONAL",
    "priceType": "OPERATING_PRICE"
  },
  "energyDirection": "FEED_OUT",
  "calculationPrice": 8.25,
  "totalSum": 16.75,
  "postponedDeregistrationDate": "1909-12-31T12:26:36.0Z",
  "resolutionTimestamp": "1917-05-04T08:56:23.0Z",
  "deliveryAddressOldDevices": {
    "boType": "BUSINESS_PARTNER",
    "structureVersion": "1",
    "salutation": "Prof. Dr.",
    "name1": "Gombert",
    "name2": "Viktor",
    "name3": "fugiat deserunt ad nulla in",
    "name4": "voluptate reprehenderit adipisicing",
    "vatId": "DE011101000",
    "creditorId": "115945",
    "emailAddress": "Cedrik.Dehmel@gmail.com",
    "website": "https://genusslich-knie.net",
    "commercialClassification": false,
    "commercialRegisterNumber": "115889",
    "courtOfRegistration": "Floderstadt",
    "partnerAddress": {
      "postalCode": "59213",
      "city": "Lenzenstadt",
      "street": "Carlo-Mierendorff-Str.",
      "houseNumber": "2",
      "poBox": "labore veniam pariatur",
      "addressSupplement": "nisi",
      "coSupplement": "Excepteur nostrud aute ut",
      "countryCode": "CU",
      "district": "Gummersbach",
      "additionalInformation": {
        "supplement1": "sint quis incididunt deserunt Lorem",
        "supplement2": "exercitation dolore laborum nulla",
        "supplement3": "deserunt Duis",
        "supplement4": "in laboris eiusmod nulla",
        "supplement5": "sint minim eu ipsum veniam"
      }
    },
    "externalCustomerNumberSupplier": "277952",
    "externalReferences": [
      {
        "externalReferenceName": "Kundennummer beim Altlieferanten",
        "externalReferenceValue": "9100589709"
      }
    ],
    "businessPartnerRole": [
      "SUPPLIER"
    ],
    "contactChannel": [
      "FAX"
    ],
    "contactPerson": {
      "boType": "CONTACT_PERSON",
      "structureVersion": "1",
      "lastName": "Wittl",
      "eMailAddress": "Korbinian42@yahoo.com",
      "phoneNumbers": [
        {
          "numberType": "PHONE_EXTENSION",
          "phoneNumber": "+49-8803-66677333"
        }
      ]
    }
  },
  "definitionType": "LOAD_CURVES",
  "positionData": [
    {
      "positionNumber": 36882346,
      "offerPositionNumber": "876721",
      "energyCapture": "NOT_CAPTURED_SEPARATELY",
      "articleNumber": "ENERGY_TAX",
      "positionAmount": "11",
      "startDate": "1917-02-16T01:16:17.0Z",
      "endDate": "1894-09-28T12:33:54.0Z",
      "isExisting": "1",
      "obisNumber": "sed Excepteur consequat ad consectetur",
      "requestReason": "CONFIGURATION_UNCHANGED",
      "generalInformation": {
        "info1": "labore pariatur sed voluptate",
        "info2": "est enim eu consequat",
        "info3": "ut",
        "info4": "qui exercitation ut deserunt",
        "info5": "anim ullamco"
      },
      "discrepancyInfo": {
        "discrepancy1": "sunt deserunt Duis id",
        "discrepancy2": "dolore proident",
        "discrepancy3": "aliquip in",
        "discrepancy4": "in ut",
        "discrepancy5": "eiusmod enim est"
      },
      "definitionType": "SWITCHING_TIME",
      "locationId": "93149650453",
      "meterRegister": 6,
      "endpointAddress": {
        "gwaManagement": "sed irure minim proident",
        "gwaAdminService": "tempor ut in",
        "gwaNTP": "sunt incididunt pariatur"
      },
      "certificateInformation": {
        "uriSubCA": "dolor in velit pariatur ut",
        "commonNameCertificate": "tempor do non",
        "serialNumberCertificate": "ad sint id"
      },
      "wakeUpPort": "in",
      "apnCommunicationData": "qui"
    }
  ],
  "remarks": [
    "In dolorum tempore at dignissimos."
  ]
}
