=== conuti-gmbh/bo4e-schema-en/schemas/v1/bo/ValuesByType2.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema-en/main/schemas/v1/bo/ValuesByType2.schema.json",
  "title": "ValuesByType2",
  "type": "object",
  "properties": {
    "boType": {
      "$ref": "../enum/BOType.schema.json",
      "default": "VALUES_BY_TYPE2"
    },
    "structureVersion": {
      "type": "string",
      "default": "1"
    },
    "configurationProduct": {
      "type": "string"
    },
    "meteringProduct": {
      "type": "string"
    },
    "targetAddress": {
      "$ref": "../com/TargetAddress.schema.json"
    },
    "issuer": {
      "$ref": "../com/Issuer.schema.json"
    },
    "certificateUser": {
      "$ref": "../com/CertificateUser.schema.json"
    },
    "configurationChangeOption": {
      "$ref": "../enum/ConfigurationChangeOption.schema.json"
    },
    "thresholds": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "../com/Threshold.schema.json"
      }
    },
    "meterRegisters": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "../com/MeterRegister.schema.json"
      }
    }
  },
  "required": [
    "boType",
    "structureVersion"
  ]
}

=== conuti-gmbh/bo4e-schema-en/docs/examples/bo/ValuesByType2.json
{
  "boType": "VALUES_BY_TYPE2",
  "structureVersion": "1",
  "configurationProduct": "proident aliquip occaecat laborum",
  "meteringProduct": "laborum ut",
  "targetAddress": {
    "targetAddress1": "ea non in",
    "targetAddress2": "nostrud elit deserunt magna amet",
    "targetAddress3": "ut do elit nisi reprehenderit",
    "targetAddress4": "laborum tempor sunt",
    "targetAddress5": "ut"
  },
  "issuer": {
    "issuer1": "adipisicing sed do",
    "issuer2": "laboris id cillum",
    "issuer3": "reprehenderit nisi",
    "issuer4": "magna sit commodo cillum",
    "issuer5": "aliqua non"
  },
  "certificateUser": {
    "certificateUser1": "dolor amet in id",
    "certificateUser2": "ut commodo irure nulla consectetur",
    "certificateUser3": "dolore reprehenderit",
    "certificateUser4": "in quis ullamco exercitation",
    "certificateUser5": "tempor quis"
  },
  "configurationChangeOption": "REQUIRED",
  "thresholds": [
    {
      "upperThreshold": 12.5,
      "lowerThreshold": 6.5,
      "configurationProduct": "KONF_0110"
    }
  ],
  "meterRegisters": [
    {
      "meterRegisterId": "356684236",
      "designation": "incididunt magna exercitation enim",
      "direction": "FEED_OUT",
      "obisCode": "Ut",
      "transformerFactor": 3,
      "unit": "CUBIC_METER",
      "offPeakCapable": "OFF_PEAK_CAPABLE",
      "consumptionType": [
        "SB"
      ],
      "interruptibility": "NUV",
      "heatUsage": "HEAT_PUMP_HEATING_COOLING",
      "concessionFee": {
        "rate": "TAS",
        "costs": 83926380.55712283,
        "category": "laboris sit in cillum ea"
      },
      "taxExempt": false,
      "integerDigits": 4,
      "decimalPlaces": 9,
      "billingRelevant": false,
      "numberOfReadings": 9,
      "meteringTimes": {
        "register": "nostrud",
        "meteringTimeDefinition": "id culpa eu ipsum",
        "offPeakCapable": "NOT_OFF_PEAK_CAPABLE"
      },
      "configuration": "consequat tempor laborum",
      "meteringProduct": "esse ut",
      "valueGranularity": "MONTHLY",
      "necessitySecondMeasurement": "NOT_PRESENT",
      "valueTransmissionPurpose": "PRESENT",
      "typeElectricMobility": "WB",
      "configurationProduct": "Lorem ut",
      "noConfigurationProduct": false,
      "loadCurveDefinition": "enim occaecat consequat ad quis",
      "purposesOfUse": [
        {
          "marketRole": "NB",
          "purpose": [
            "REACTIVE_ENERGY_BILLING_OPERATIONS_MANAGEMENT"
          ]
        }
      ],
      "usagePurposeNB": "do ullamco magna non",
      "usagePurposeLF": "ex Duis",
      "usagePurposeUENB": "incididunt cupidatat id",
      "noProduct": true
    }
  ]
}
